name: story_line
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12
  page_transition: ^1.1.6
  flutter_svg: ^0.19.0
  auto_size_text: ^2.1.0
  url_launcher: ^5.7.2
  flutter_webview_plugin: ^0.3.11
  dio: ^3.0.10
  equatable: ^1.2.5
  flutter_bloc: ^6.0.5
  cached_network_image: ^2.3.2+1
  sliding_up_panel: ^1.0.2
  device_info: any
  charts_flutter: 0.9.0
  mp_chart: ^0.2.2
  modal_progress_hud: ^0.1.3
  date_range_picker: ^1.0.6
  date_format: ^1.0.9
  keyboard_avoider: 0.1.2

dev_dependencies:
  image_res: ^0.2.3
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/news/
    - assets/images/notification/
    - assets/images/profile/
    - assets/images/arrow/
    - assets/fonts/

  fonts:
    - family: proxima
      fonts:
        - asset: assets/fonts/Proxima Nova Reg.ttf
          weight: 500
    - family: proxima-bold
      fonts:
        - asset: assets/fonts/Proxima Nova Bold.ttf
          weight: 800
    - family: proxima-light
      fonts:
        - asset: assets/fonts/Proxima Nova Light.ttf
          weight: 200
flutter_icons:
  android: false
  ios: false
